#!/usr/bin/env bash

if [ $# == 0 ]; then
	echo "easy to filter proxy web data to plain and clear proxylist"
	echo "usage:filter-proxy -3 filename (http/https filter)"
	echo "     :filter-proxy -4 filename (socks4 filter)"
	echo "     :filter-proxy -5 filename (socks5 filter)"
	exit  -1
fi

tmpfile=$RANDOM

cat <<BOF >$tmpfile
random_chain
quiet_mode
proxy_dns
tcp_read_time_out 20000 
tcp_connect_time_out 2000 
[ProxyList]
BOF

if [ ${1} == '-3' ]; then
cat $2|grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}"|awk '{print "http",$1,$2}'>>$tmpfile 
fi

if [ ${1} == '-4' ]; then
cat $2|grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}"|awk '{print "socks4",$1,$2}'>>$tmpfile 
fi

if [ ${1} == '-5' ]; then
cat $2|grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}"|awk '{print "socks5",$1,$2}'>>$tmpfile 
fi

sudo mv $tmpfile /etc/proxychains.conf
less /etc/proxychains.conf
