#!/bin/bash

iptables -F
iptables -X
iptables -Z
iptables -P INPUT DROP
iptables -P OUTPUT ACCEPT
iptables -P FORWARD DROP

iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -i wlx8c210adff019 -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

#DNS
iptables -A OUTPUT -o wlx8c210adff019 -p TCP --sport 1024:65535 --dport 53 -m state --state NEW -j ACCEPT
iptables -A OUTPUT -o wlx8c210adff019 -p UDP --sport 1024:65535 --dport 53 -m state --state NEW -j ACCEPT

iptables -A OUTPUT -o wlx8c210adff019 -p TCP --sport 1024:65535 --dport 953 -m state --state NEW -j ACCEPT
iptables -A OUTPUT -o wlx8c210adff019 -p UDP --sport 1024:65535 --dport 953 -m state --state NEW -j ACCEPT

#HTTP
iptables -A OUTPUT -o wlx8c210adff019 -p TCP --sport 1024:65535 --dport 80 -m state --state NEW -j ACCEPT


#HTTPS

iptables -A OUTPUT -o wlx8c210adff019 -p TCP --sport 1024:65535 --dport 443 -j ACCEPT

#EMAIL
iptables -A OUTPUT -o wlx8c210adff019 -p TCP --sport 1024:65535 --dport 110 -j ACCEPT
iptables -A OUTPUT -o wlx8c210adff019 -p TCP --sport 1024:65535 --dport 25 -j ACCEPT

#FTP
iptables -A OUTPUT -o wlx8c210adff019 -p TCP --sport 1024:65535 --dport 20 -j ACCEPT
iptables -A OUTPUT -o wlx8c210adff019 -p TCP --sport 1024:65535 --dport 21 -j ACCEPT

iptables -A INPUT -i wlx8c210adff019 -p TCP --dport 1024:65535 --sport 21 -j ACCEPT
iptables -A INPUT -i wlx8c210adff019 -p TCP --dport 1024:65535 --sport 20 -j ACCEPT
#POP3S
iptables -A OUTPUT -o wlx8c210adff019 -p TCP --sport 1024:65535 --dport 995 -j ACCEPT

#NTP
iptables -A OUTPUT -o wlx8c210adff019 -p TCP --sport 1024:65535 --dport 123 -j ACCEPT

#allow ping request
iptables -A INPUT -p icmp --icmp-type echo-request -j ACCEPT
iptables -A OUTPUT -p icmp --icmp-type echo-reply -j ACCEPT

#allow ssh incomming

iptables -A INPUT -s 192.168.40.101/32 -p tcp -m tcp --dport 22 -j ACCEPT
iptables -A OUTPUT -d 192.168.40.101/32 -p tcp -m tcp --sport 22 -j ACCEPT

#allow dns requeset incomming
iptables -A INPUT -i wlx8c210adff019 -p tcp -m tcp --dport 53 -j ACCEPT
iptables -A INPUT -i wlx8c210adff019 -p udp -m udp --dport 53 -j ACCEPT

iptables -A OUTPUT -o wlx8c210adff019 -p tcp -m tcp --sport 53 -j ACCEPT
iptables -A OUTPUT -o wlx8c210adff019 -p udp -m udp --sport 53 -j ACCEPT

#allow http request incomming
iptables -A INPUT -i wlx8c210adff019 -p tcp -m tcp --dport 80 -j ACCEPT
iptables -A INPUT -i wlx8c210adff019 -p tcp -m tcp --dport 443 -j ACCEPT

iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT


