#!/usr/bin/env bash
sudo chattr -i /etc/resolv.conf
sudo chmod 644 /etc/resolv.conf
sudo echo "nameserver 127.0.0.1" > /etc/resolv.conf
sudo chmod 444 /etc/resolv.conf
sudo chattr +i /etc/resolv.conf
